# hyprlock.conf
# Tela de bloqueio simples: fundo sólido escuro + campo de senha + relógio.

background {
    monitor =
    color = rgba(11, 11, 11, 1.0)
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    outer_color = rgba(88888888)
    inner_color = rgba(11, 11, 11, 0.8)
    font_color = rgb(255, 255, 255)
    fade_on_empty = true
    placeholder_text = <span foreground="##ffffff">Senha...</span>
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(255, 255, 255, 1)
    font_size = 64
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%d/%m/%Y')"
    color = rgba(255, 255, 255, 0.8)
    font_size = 18
    position = 0, 60
    halign = center
    valign = center
}
