# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Gerado automaticamente pelo wallust a partir do wallpaper atual.
# NAO EDITE ESTE ARQUIVO A MAO — sobrescrito a cada `wallust run`.
# Editar o template em: ~/.config/wallust/templates/kitty-colors.conf
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

foreground #C2A6A5
background #170D0C
cursor     #A07B7A

color0  #230000
color1  #631B1B
color2  #771F1F
color3  #6D1E1E
color4  #5D1D1D
color5  #702020
color6  #64231F
color7  #AA8F8E
color8  #775F5E
color9  #832121
color10 #A62727
color11 #962525
color12 #782424
color13 #9A2A2A
color14 #852C28
color15 #CCBFBE
