# Configuração de sensibilidade do mouse para SDDM / Xorg
# Igualando ao Hyprland: accel_profile = "flat", sensitivity = 0
Section "InputClass"
    Identifier "system-mouse"
    MatchIsPointer "on"
    Driver "libinput"
    Option "AccelProfile" "flat"
    Option "AccelSpeed" "0"
EndSection
